# Generated by Django 3.0.2 on 2020-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviewable_user',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
